# utils/enhanced_report.py
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from PIL import Image as PILImage

def create_enhanced_pdf_report(result_data, output_folder):
    """Create enhanced PDF report with better formatting"""
    
    # Create filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    patient_name_clean = result_data['patient_name'].replace(' ', '_').replace('/', '_')
    filename = f"Coronary_Report_{patient_name_clean}_{timestamp}.pdf"
    filepath = os.path.join(output_folder, filename)
    
    # Create PDF
    c = canvas.Canvas(filepath, pagesize=A4)
    width, height = A4
    
    # Page 1: Cover Page
    # Background
    c.setFillColorRGB(0.95, 0.95, 0.98)
    c.rect(0, 0, width, height, fill=1)
    
    # Logo/Title
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.setFont("Helvetica-Bold", 36)
    c.drawCentredString(width/2, height - 3*inch, "CORONARY AI")
    
    c.setFillColorRGB(0.3, 0.3, 0.3)
    c.setFont("Helvetica", 18)
    c.drawCentredString(width/2, height - 3.8*inch, "Stenosis Detection Report")
    
    # Patient Info Box
    c.setFillColorRGB(1, 1, 1)
    c.setStrokeColorRGB(0.2, 0.4, 0.6)
    c.setLineWidth(2)
    info_box_y = height - 6*inch
    c.roundRect(1*inch, info_box_y, width - 2*inch, 2*inch, 10, fill=1, stroke=1)
    
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1.5*inch, info_box_y + 1.6*inch, "PATIENT INFORMATION")
    
    c.setFillColorRGB(0.3, 0.3, 0.3)
    c.setFont("Helvetica", 12)
    c.drawString(1.5*inch, info_box_y + 1.2*inch, f"Name: {result_data['patient_name']}")
    c.drawString(1.5*inch, info_box_y + 0.9*inch, f"Date: {result_data['timestamp'][:10]}")
    c.drawString(1.5*inch, info_box_y + 0.6*inch, f"Time: {result_data['timestamp'][11:19]}")
    c.drawString(1.5*inch, info_box_y + 0.3*inch, f"Session ID: {result_data['session_id']}")
    
    # Status indicator
    status_y = info_box_y - 1*inch
    if result_data['stenosis_detected']:
        c.setFillColorRGB(0.8, 0, 0)  # Red for positive
        status_text = f"POSITIVE - {result_data['detection_count']} STENOSIS DETECTED"
    else:
        c.setFillColorRGB(0, 0.6, 0)  # Green for negative
        status_text = "NEGATIVE - NO STENOSIS DETECTED"
    
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width/2, status_y, status_text)
    
    # Footer
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica", 9)
    c.drawCentredString(width/2, 1*inch, 
                       "This report is generated by AI system for research purposes")
    c.drawCentredString(width/2, 0.8*inch, 
                       "Clinical correlation and physician review required")
    
    c.showPage()
    
    # Page 2: Images
    # Header
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 1*inch, "IMAGE ANALYSIS")
    
    # Original Image
    if 'original_filename' in result_data and result_data['original_filename']:
        original_path = os.path.join('data/uploads', result_data['original_filename'])
        if os.path.exists(original_path):
            try:
                # Add image with border
                c.setStrokeColorRGB(0.8, 0.8, 0.8)
                c.setLineWidth(2)
                c.rect(0.5*inch, height - 4*inch, 3.5*inch, 3*inch)
                
                c.setFillColorRGB(0.3, 0.3, 0.3)
                c.setFont("Helvetica-Bold", 12)
                c.drawString(0.6*inch, height - 4.2*inch, "Original Angiogram")
                
                # Add actual image (scaled)
                img = PILImage.open(original_path)
                img.thumbnail((200, 200))
                temp_path = original_path + "_thumb.png"
                img.save(temp_path)
                
                c.drawImage(temp_path, 0.6*inch, height - 3.9*inch, 
                           width=3.3*inch, height=2.7*inch)
                os.remove(temp_path)
                
            except Exception as e:
                print(f"Error adding original image: {e}")
                c.setFillColorRGB(0.7, 0.7, 0.7)
                c.setFont("Helvetica", 10)
                c.drawString(0.6*inch, height - 3*inch, "Original image not available")
    
    # Processed Image
    if result_data['stenosis_detected'] and 'processed_filename' in result_data:
        processed_path = os.path.join('data/results', result_data['processed_filename'])
        if os.path.exists(processed_path):
            try:
                # Add image with colored border
                c.setStrokeColorRGB(0, 0.8, 0)  # Green border
                c.setLineWidth(3)
                c.rect(4.5*inch, height - 4*inch, 3.5*inch, 3*inch)
                
                c.setFillColorRGB(0, 0.5, 0)
                c.setFont("Helvetica-Bold", 12)
                c.drawString(4.6*inch, height - 4.2*inch, "Analysis Result")
                
                # Add processed image
                img = PILImage.open(processed_path)
                img.thumbnail((200, 200))
                temp_path = processed_path + "_thumb.png"
                img.save(temp_path)
                
                c.drawImage(temp_path, 4.6*inch, height - 3.9*inch, 
                           width=3.3*inch, height=2.7*inch)
                os.remove(temp_path)
                
                # Add legend
                c.setFillColorRGB(0, 0.6, 0)
                c.setFont("Helvetica-Bold", 10)
                c.drawString(4.6*inch, height - 4.5*inch, "✓ Green boxes show detected stenosis")
                
            except Exception as e:
                print(f"Error adding processed image: {e}")
    
    # Detection Details
    y_position = height - 5*inch
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(0.5*inch, y_position, "DETECTION DETAILS")
    y_position -= 0.3*inch
    
    if result_data['stenosis_detected'] and 'detections' in result_data:
        for i, detection in enumerate(result_data['detections'], 1):
            # Create a box for each detection
            c.setFillColorRGB(0.95, 0.95, 0.98)
            c.setStrokeColorRGB(0.8, 0.8, 0.8)
            c.setLineWidth(1)
            c.roundRect(0.5*inch, y_position - 0.8*inch, width - 1*inch, 0.7*inch, 5, fill=1, stroke=1)
            
            # Detection info
            c.setFillColorRGB(0.3, 0.3, 0.3)
            c.setFont("Helvetica-Bold", 12)
            c.drawString(0.7*inch, y_position - 0.4*inch, f"STENOSIS #{i}")
            
            c.setFont("Helvetica", 10)
            info = f"Location: X={detection['bbox'][0]:.1f}, Y={detection['bbox'][1]:.1f} | "
            info += f"Segment: {detection['segment'].get('segment_name', 'Unknown')} | "
            info += f"Artery: {detection['artery'].get('artery_name', 'Unknown')}"
            c.drawString(0.7*inch, y_position - 0.6*inch, info)
            
            y_position -= 1*inch
            
            # Add new page if running out of space
            if y_position < 2*inch and i < len(result_data['detections']):
                c.showPage()
                y_position = height - 1*inch
                c.setFillColorRGB(0.2, 0.4, 0.6)
                c.setFont("Helvetica-Bold", 18)
                c.drawString(0.5*inch, y_position, "DETECTION DETAILS (CONTINUED)")
                y_position -= 0.3*inch
    
    c.showPage()
    
    # Page 3: Summary and Recommendations
    # Clinical Summary
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 1*inch, "CLINICAL SUMMARY")
    
    y_position = height - 2*inch
    
    c.setFillColorRGB(0.3, 0.3, 0.3)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(0.5*inch, y_position, "Findings:")
    y_position -= 0.3*inch
    
    c.setFont("Helvetica", 12)
    if result_data['stenosis_detected']:
        findings = f"Coronary angiogram analysis reveals {result_data['detection_count']} "
        findings += "stenosis location(s) in the coronary arteries."
    else:
        findings = "Coronary angiogram analysis shows no evidence of coronary artery stenosis."
    
    c.drawString(0.7*inch, y_position, findings)
    y_position -= 0.5*inch
    
    # Affected Arteries
    if result_data['stenosis_detected']:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(0.5*inch, y_position, "Affected Arteries:")
        y_position -= 0.3*inch
        
        arteries = list(set([d['artery'].get('artery_name', 'Unknown') for d in result_data['detections']]))
        c.setFont("Helvetica", 12)
        for artery in arteries:
            c.drawString(0.7*inch, y_position, f"• {artery}")
            y_position -= 0.3*inch
        
        y_position -= 0.2*inch
    
    # Recommendations
    c.setFillColorRGB(0.2, 0.4, 0.6)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(0.5*inch, y_position, "RECOMMENDATIONS:")
    y_position -= 0.4*inch
    
    c.setFillColorRGB(0.3, 0.3, 0.3)
    c.setFont("Helvetica", 11)
    
    if result_data['stenosis_detected']:
        recommendations = [
            "1. Quantitative Coronary Angiography (QCA) for precise measurements",
            "2. Fractional Flow Reserve (FFR) assessment if indicated",
            "3. Clinical correlation with patient symptoms",
            "4. Consider multi-disciplinary team review",
            "5. Follow-up as per clinical guidelines",
            "6. Pharmacological optimization review"
        ]
    else:
        recommendations = [
            "1. Continue routine clinical follow-up",
            "2. Maintain optimal medical therapy",
            "3. Regular cardiovascular risk assessment",
            "4. Lifestyle modification counseling",
            "5. Follow preventive cardiology guidelines"
        ]
    
    for rec in recommendations:
        c.drawString(0.7*inch, y_position, rec)
        y_position -= 0.25*inch
    
    # Disclaimer
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica", 9)
    disclaimer_y = 1*inch
    disclaimer = [
        "IMPORTANT DISCLAIMER:",
        "This report is generated by an automated AI system for research and demonstration purposes only.",
        "It is not intended for clinical decision-making without review by a qualified medical professional.",
        "All findings should be correlated with clinical assessment and other diagnostic tests.",
        f"Report generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "CoronaryAI Stenosis Detection System v1.0"
    ]
    
    for line in disclaimer:
        c.drawCentredString(width/2, disclaimer_y, line)
        disclaimer_y -= 0.15*inch
    
    # Save PDF
    c.save()
    print(f"✅ Enhanced PDF report generated: {filepath}")
    return filepath